what-is-a-thing:
    heading: "What is a thing?"
    summary: "On constraints, meaning, and what learning algorithms might be missing."
    date: "10/01/2026"
    careless-wonder: true

update-rules:
    heading: "Update Rules"
    summary: "On architectures of learning systems, and their dynamics."
    date: "14/01/2026"
    careless-wonder: true
